-- MySQL Script generated by MySQL Workbench
-- lun 04 abr 2022 19:44:40 CEST
-- Model: New Model    Version: 1.0

# authors: Daniel Corrales, Daniel Berdasco, María Calvo
# usuario: rest
# contraseña: rest
CREATE USER 'rest'@'localhost' IDENTIFIED BY 'rest';
GRANT ALL PRIVILEGES ON GeoETSIINF.* TO 'rest'@'localhost';
CREATE USER 'rest'@'127.0.0.1' IDENTIFIED BY 'rest';
GRANT ALL PRIVILEGES ON GeoETSIINF.* TO 'rest'@'127.0.0.1';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GeoETSIINF
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GeoETSIINF` ;
CREATE SCHEMA IF NOT EXISTS `GeoETSIINF` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `GeoETSIINF` ;

-- -----------------------------------------------------
-- Table `GeoETSIINF`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeoETSIINF`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `GeoETSIINF`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `GeoETSIINF`.`tesoro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeoETSIINF`.`Tesoro` ;

CREATE TABLE IF NOT EXISTS `GeoETSIINF`.`Tesoro` (
  `idTesoro` INT NOT NULL AUTO_INCREMENT,
  `tamanio` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `dificultad` VARCHAR(45) NOT NULL,
  `tipoTerreno` VARCHAR(45) NOT NULL,
  `latitud` FLOAT NOT NULL,
  `longitud` FLOAT NOT NULL,
  `creador` INT NOT NULL,
  `pista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTesoro`),
  INDEX `fk_Tesoro_Usuario1_idx` (`creador` ASC),
    FOREIGN KEY (`creador`)
    REFERENCES `GeoETSIINF`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeoETSIINF`.`Usuario_esamigode_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeoETSIINF`.`Usuario_esamigode_Usuario` ;

CREATE TABLE IF NOT EXISTS `GeoETSIINF`.`Usuario_esamigode_Usuario` (
  `creador` INT NOT NULL,
  `Usuario_idAmigo` INT NOT NULL,
  PRIMARY KEY (`creador`, `Usuario_idAmigo`),
  INDEX `fk_Usuario_has_Usuario_Amigo_idx` (`Usuario_idAmigo` ASC),
  INDEX `fk_Usuario_has_Usuario_Usuario_idx` (`creador` ASC),
    FOREIGN KEY (`creador`)
    REFERENCES `GeoETSIINF`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`Usuario_idAmigo`)
    REFERENCES `GeoETSIINF`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeoETSIINF`.`Usuario_encuentra_tesoro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeoETSIINF`.`Usuario_encuentra_Tesoro` ;

CREATE TABLE IF NOT EXISTS `GeoETSIINF`.`Usuario_encuentra_Tesoro` (
  `creador` INT NOT NULL,
  `Tesoro_idTesoro` INT NOT NULL,
  PRIMARY KEY (`creador`, `Tesoro_idTesoro`),
  INDEX `fk_Usuario_has_Tesoro_Tesoro1_idx` (`Tesoro_idTesoro` ASC),
  INDEX `fk_Usuario_has_Tesoro_Usuario1_idx` (`creador` ASC),
    FOREIGN KEY (`creador`)
    REFERENCES `GeoETSIINF`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`Tesoro_idTesoro`)
    REFERENCES `GeoETSIINF`.`Tesoro` (`idTesoro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO Usuario (nombre, correo, edad, localidad) VALUES ('juan', 'juan@gmail.com', 32, 'madrid');
INSERT INTO Usuario (nombre, correo, edad, localidad) VALUES ('pepe', 'pepe@gmail.com', 20, 'valencia');
INSERT INTO Usuario (nombre, correo, edad, localidad) VALUES ('juan', 'juan@gmail.com', 32, 'madrid');
INSERT INTO Usuario (nombre, correo, edad, localidad) VALUES ('pedro', 'pedro@gmail.com', 19, 'zaragoza');
INSERT INTO Usuario (nombre, correo, edad, localidad) VALUES ('santi', 'santi@gmail.com', 50, 'toledo');
UPDATE Usuario SET edad = 102, correo = 'juanito@gmail.com', localidad = 'madrid' WHERE idUsuario = 2;
#DELETE FROM Usuario WHERE idUsuario = 6;
#DELETE FROM Usuario WHERE idUsuario = 1;
#SELECT * FROM Usuario WHERE idUsuario = 2;
#SELECT * FROM Usuario WHERE nombre LIKE '%' ;
#SELECT * FROM Usuario;

INSERT INTO Tesoro (tamanio, fecha, dificultad, tipoTerreno, latitud, longitud, creador, pista) VALUES (320, '2022-04-18', 'dificil', 'agua', -2.45567, 123.23145, 2, 'mira al oeste');
INSERT INTO Tesoro (tamanio, fecha, dificultad, tipoTerreno, latitud, longitud, creador, pista) VALUES (40, '2022-12-04', 'facil', 'tierra', 6.45678, 74.12345, 3, 'busca bien');
INSERT INTO Tesoro (tamanio, fecha, dificultad, tipoTerreno, latitud, longitud, creador, pista) VALUES (66, '2021-12-04', 'dificil', 'agua', 58.45678, 1.12345, 3, 'bajo el mar');
INSERT INTO Tesoro (tamanio, fecha, dificultad, tipoTerreno, latitud, longitud, creador, pista) VALUES (10, '2017-04-08', 'medio', 'tierra', 3.4567, 3.2345, 2, 'pista');
#SELECT * FROM Tesoro;
#SELECT idTesoro FROM Tesoro WHERE creador LIKE '%' AND fecha LIKE '%' AND dificultad LIKE '%' AND tamanio LIKE '%' AND tipoTerreno LIKE '%' LIMIT 0,10 ;
#SELECT idTesoro FROM Tesoro WHERE dificultad LIKE '%' AND fecha LIKE '%' ORDER BY (ABS(latitud - '0') + ABS(longitud - '0')) LIMIT 0,10;

INSERT INTO Usuario_encuentra_Tesoro (creador, Tesoro_idTesoro) VALUES (2,3);
#SELECT * FROM Usuario_encuentra_Tesoro;


INSERT INTO Usuario_esamigode_Usuario (creador, Usuario_idAmigo) VALUES (2, 3);
INSERT INTO Usuario_esamigode_Usuario (creador, Usuario_idAmigo) VALUES (6, 3);
INSERT INTO Usuario_esamigode_Usuario (creador, Usuario_idAmigo) VALUES (5, 3);

#SELECT * FROM Usuario WHERE idUsuario = (SELECT Usuario_idAmigo FROM Usuario_esamigode_Usuario WHERE creador = 2) AND nombre LIKE '%' LIMIT 0,10;
#SELECT * FROM Usuario_esamigode_Usuario;
#DELETE FROM Usuario_esamigode_Usuario WHERE Usuario_idAmigo = 3;
#SELECT * FROM Usuario WHERE idUsuario = '%';;
#SELECT COUNT(Tesoro_idTesoro) FROM Usuario_encuentra_Tesoro WHERE creador = '%';
#SELECT idTesoro FROM Tesoro WHERE creador = '%' ORDER BY fecha DESC;
#SELECT COUNT(Usuario_idAmigo) FROM Usuario_esamigode_Usuario WHERE creador = '%';
#SELECT COUNT(creador) FROM Tesoro WHERE creador = '%';
#SELECT idTesoro FROM Tesoro WHERE idTesoro = (SELECT idTesoro FROM Usuario_encuentra_Tesoro WHERE creador = '%') ORDER BY fecha DESC LIMIT 5;